export const skills = [
  {
    id: 1,
    category: "Frontend Development",
    count: 7,
    icon: "ri-terminal-window-line",
    color: "text-[#b35aff]",
    technologies: [ "HTML5", "CSS3", "JavaScript", "React", "Tailwind CSS", "Bootstrap", "Material UI"],
  },
  {
    id: 2,
    category: "Backend Development",
    count: 3,
    icon: "ri-server-line",
    color: "text-[#3b82f6]",
    technologies: ["Node.js", "Express", "RESTful APIs"],
  },
  {
    id: 3,
    category: "Database Management",
    count: 3,
    icon: "ri-database-2-line",
    color: "text-[#25d464]",
    technologies: ["MongoDB", "MySQL", "PostgreSQL"],
  },
  {
    id: 4,
    category: "Tools",
    count: 5,
    icon: "ri-terminal-line",
    color: "text-[#ef4444]",
    technologies: ["Git", "GitHub", "Postman", "Vercel", "Netlify"],
  },
  {
    id: 5,
    category: "Web Technologies",
    count: 3,
    icon: "ri-global-line",
    color: "text-[#06bbd9]",
    technologies: ["RESTful Services", "OAuth", "JWT"],
  },
  {
    id: 6,
    category: "Programming Languages",
    count: 4,
    icon: "ri-code-s-slash-line",
    color: "text-[#eab308]",
    technologies: ["JavaScript", "Python", "Java", "C"],
  },
];
